import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    kotlin("jvm") version "2.4.10"
    // io.ratpack.ratpack-java removed: every release of it calls the `compile`
    // configuration, which Gradle dropped in 7.0. This project never used
    // ratpack directly -- it arrives transitively via dc2f-edit-api, which now
    // declares ratpack-core itself.

    // Apply the application plugin to add support for building a CLI application.
    application
}

// The RatpackContinuousRun block that lived here went with the plugin. It only
// set flattenClassloaders for `gradle -t run`, i.e. `dc2f.sh serve`. The server
// still watches web/content itself, so content edits reload as before; a change
// to Kotlin sources now needs a restart.

repositories {
    // jcenter() dropped: shut down in 2021 and removed in Gradle 9.
    mavenCentral()
    maven("https://jitpack.io")
    maven("https://oss.sonatype.org/content/groups/public/")
}

val dc2fVersion = "0.2.3-SNAPSHOT"

tasks.withType<KotlinCompile> {
    // sourceCompatibility dropped: KotlinCompile stopped extending AbstractCompile
    // in Kotlin 1.9, and it was a no-op here regardless (no Java sources).
    // kotlinOptions was removed in Kotlin 2.2; compilerOptions replaces it, and
    // -Xjvm-default became -jvm-default ("no-compatibility" == the old "all").
    compilerOptions {
        freeCompilerArgs.add("-jvm-default=no-compatibility")
    }
}

// Pins both the Java and Kotlin targets together. Setting only
// compilerOptions.jvmTarget lets compileJava follow whatever JDK is running and
// Gradle then rejects the mismatch. Gradle 9 requires JDK 17 to run anyway.
kotlin {
    jvmToolchain(17)
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("com.dc2f:dc2f:$dc2fVersion")
    implementation("com.dc2f:dc2f-common:$dc2fVersion")
    implementation("org.unbescape:unbescape:1.1.6.RELEASE")


    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

application {
    // Define the main class for the application
    // mainClassName was removed in Gradle 8.
    mainClass.set("com.dc2f.starter.AppKt")

    // JDK 16 turned strong encapsulation on by default, so commons-lang3's
    // ReflectionToStringBuilder reaching into java.util.Optional now throws
    // InaccessibleObjectException instead of warning. It is swallowed inside
    // TRACE logging, so nothing breaks -- it just fills `serve` output with
    // "Log message invocation failed".
    //
    // Note the "=" form: each list entry becomes one argv element, so
    // "--add-opens java.base/java.util=ALL-UNNAMED" would reach the JVM as a
    // single token with a space in it and fail to parse.
    applicationDefaultJvmArgs = listOf(
        "--add-opens=java.base/java.lang=ALL-UNNAMED",
        "--add-opens=java.base/java.util=ALL-UNNAMED"
    )
}
